# Generated by Django 4.1.1 on 2022-09-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiFamilia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
